name: Go
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
defaults:
  run:
    working-directory: area_of_a_square
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build
      run: |
        cd area_of_a_square
        go build main.go
        ls -lht
