name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build
      run: go build main
      env:
        GOPATH: $GOPATH/area_of_a_square
    - name: Test
      run: go test main
      env:
        GOPATH: $GOPATH/area_of_a_square
